services:
  - type: web
    name: webnovacrew
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
